source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#inhibit_all_warnings!

def common
    pod 'WeexSDK', :path=>'sdk/'
    pod 'WXDevtool', '0.8.0'
    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2'
    pod 'ATSDK-Weex', '0.0.1'
    pod 'extobjc'
end

target 'QSWeexDemo' do
    common
end

target 'QSWeexDemoUITests' do
    common
end


