# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'QSUseLevelDBDemo' do
    #LevelDB
    pod 'Objective-LevelDB'
    #YYModel
    pod 'YYModel'
end
